apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Release.Name }}
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
  type: NodePort
status:
  loadBalancer: {}
