apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      initContainers:
      - name: python
        image: python
        command: ['/bin/sh', '-c', 'echo "Hello World!"']
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 9090

